   ##############################
   #                            #
   #            MAIN            #
   #                            #
   ##############################

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages/

frontend:
  themes: !include_dir_merge_named themes

config:
api:
map:
mobile_app:
sun:  
logger:
  default: info
zeroconf:
  default_interface: true

hacs:
   token: !secret hacs_token

calendar:
  - platform: caldav
    url: !secret calendar_url
    username: !secret calendar_user
    password: !secret calendar_psw
    calendars:
      - 'Casa'

   ##############################
   #                            #
   #             UI             #
   #                            #
   ##############################

lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    ndr-ui:
      mode: yaml
      title: NdRUI
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: ndrui.yaml 
    ndr-hkui:
      mode: yaml
      title: NdR HomeKit UI
      icon: mdi:apple
      show_in_sidebar: true
      filename: ndr-hkui.yaml     

   ##############################
   #                            #
   #        INTEGRAZIONI        #
   #                            #
   ##############################

#LG WebOS
webostv:
  host: 192.168.1.120
  name: TV Sala
  turn_on_action:
    service: media_player.turn_on
    entity_id: media_player.tv_lg_sala #Entità creata con SmartIR per accendere la TV con Broadlink

#SmartIR
smartir:
  
media_player:
  - platform: smartir
    name: TV LG Sala
    device_code: 180891
    controller_data: remote.rm3_sala_remote
    power_sensor: media_player.tv_sala #Usa l'integrazione WebOS per rilevare acceso/spento

#DuckDNS
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret chat_id_andre
      - !secret chat_id_mary

camera:
  - platform: ffmpeg
    name: Yi Camera - Sala
    input: rtsp://192.168.1.140/ch0_0.h264
  
  - platform: ffmpeg
    name: Yi Camera - Camera
    input: rtsp://192.168.1.141/ch0_0.h264

   ##############################
   #                            #
   #           NOTIFY           #
   #                            #
   ##############################
      
notify:
  - name: Andrea
    platform: telegram
    chat_id: !secret chat_id_andre
  
  - name: Mary
    platform: telegram
    chat_id: !secret chat_id_mary

  - name: famiglia
    platform: group
    services:
      - service: andrea
      - service: mary

   ##############################
   #                            #
   #            VARIE           #
   #                            #
   ##############################

#Add-on
browser_mod:
  disable:
    - all

# Text to speech
tts:
  - platform: google_translate

#Shell Comands
#Comandi PC
shell_command: 
  shutdown_z800: 'curl -k http://192.168.1.40:8000/?action=System.Shutdown'
  restart_z800: 'curl -k http://192.168.1.40:8000/?action=System.Restart'

   ##############################
   #                            #
   #           TRACKER          #
   #                            #
   ##############################

device_tracker:
- platform: fritz
  host: 192.168.1.1
  consider_home: 180
  new_device_defaults:
    track_new_devices: false